pipeline {
    agent {
        label 'ubuntu'
    }
    tools {
        maven 'maven-apache-3.8.4' 
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -f cicd/java-app/pom.xml -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -f cicd/java-app/pom.xml test'
            }
            post {
                always {
                    junit 'cicd/java-app/target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
